apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c8-labs-32-grafana
  namespace: c8-labs-32
  labels:
    app: grafana
  annotations:
    kubernetes.io/ingress.class: "nginx"
    meta.helm.sh/release-namespace: c8-labs-32
    nginx.ingress.kubernetes.io/backend-protocol: "http"
    kubernetes.io/ingress.allow-http: "false"  # on ingress, we only allow secure line. 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #networking.gke.io/managed-certificates: c8-zeebe-gw-cert # Demo env does not require cert
spec:
  tls:
    - hosts:
        - c8-labs-32-grafana.makelabs.in
      secretName: cf-origin-cert
  ingressClassName: "nginx"
  rules:
    - host: c8-labs-32-grafana.makelabs.in
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000
