apiVersion: v1
kind: Service
metadata:
  name: c8-labs-32-keycloak
  namespace: c8-labs-32
  #annotations:
    #cloud.google.com/backend-config: '{"default": "keycloak-backendconfig"}'
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
    - name: metrics
      protocol: TCP
      port: 82
      targetPort: 8082
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c8-labs-32-ingress-https
  namespace: c8-labs-32
  labels:
    app: camunda-platform
    app.kubernetes.io/instance: c8-labs-32
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/part-of: camunda-platform
  annotations:
    kubernetes.io/ingress.class: "nginx"
    meta.helm.sh/release-name: c8-labs-32
    meta.helm.sh/release-namespace: c8-labs-32
    kubernetes.io/ingress.allow-http: "false"  # on ingress, we only allow HTTPS. 
    #networking.gke.io/managed-certificates: c8-managed-cert # shift to cf origin cert
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Tell GKE to use HTTPS to backend
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/proxy-ssl-secret: "c8-labs-ingress-nginx/custom-ca"
    #nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    #nginx.ingress.kubernetes.io/proxy-ssl-verify-depth: "2"    
spec:
  tls:
    - hosts:
        - c8-labs-32.makelabs.in
      secretName: cf-origin-cert
  ingressClassName: "nginx"
  rules:
    - host: c8-labs-32.makelabs.in
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: c8-labs-32-keycloak
                port:
                  number: 443