apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${UNAMESPACE}-ingress-keycloak
  namespace: ${UNAMESPACE}
  labels:
    app: camunda-platform
    app.kubernetes.io/instance: ${UNAMESPACE}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: camunda-platform
    app.kubernetes.io/part-of: camunda-platform
  annotations:
    kubernetes.io/ingress.class: "nginx"

    # Force HTTPS only
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    # Backend is HTTP (NOT HTTPS)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

    # Optional: Large request support (Keycloak sometimes needs bigger buffers)
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: "nginx"

  tls:
    - hosts:
        - ${UNAMESPACE}.makelabs.in
      secretName: cf-origin-cert

  rules:
    - host: ${UNAMESPACE}.makelabs.in
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: ${UNAMESPACE}-keycloak
                port:
                  number: 80
