apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: c8-managed-cert
  namespace: c8-labs-31
spec:
  domains:
    - c8-labs-31.makelabs.in
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c8-ingress
  namespace: c8-labs-31
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: c8-managed-cert
    networking.gke.io/backend-protocol: "HTTP"  # Tell GKE to use HTTP to backend
    cloud.google.com/healthcheck-path: "/console"
spec:
  rules:
    - host: c8-labs-31.makelabs.in
      http:
        paths:
          - path: /console
            pathType: Prefix
            backend:
              service:
                name: camunda-console
                port:
                  number: 80
          - path: /identity
            pathType: Prefix
            backend:
              service:
                name: camunda-identity
                port:
                  number: 80
          - path: /operate
            pathType: Prefix
            backend:
              service:
                name: camunda-operate
                port:
                  number: 80
          - path: /tasklist
            pathType: Prefix
            backend:
              service:
                name: camunda-tasklist
                port:
                  number: 80
          - path: /optimize
            pathType: Prefix
            backend:
              service:
                name: camunda-optimize
                port:
                  number: 80
          - path: /auth/
            pathType: Prefix
            backend:
              service:
                name: camunda-keycloak
                port:
                  number: 80