apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c8-labs-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwx
