apiVersion: v1
kind: ResourceQuota
metadata:
  name: c8-labs-ns-quota
  namespace: ${UNAMESPACE}
spec:
  hard:
    # Compute
    requests.cpu: "6"
    limits.cpu: "10"

    requests.memory: 12Gi
    limits.memory: 20Gi

    # Objects
    pods: "18"
    services: "20"
    configmaps: "20"
    secrets: "30"

    # Storage
    persistentvolumeclaims: "8"
    requests.storage: 40Gi