apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolkit-app
  namespace: c8-labs-32
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolkit-app
  template:
    metadata:
      labels:
        app: toolkit-app
    spec:
      containers:
      - name: toolkit-app
        image: asia-south2-docker.pkg.dev/c8-labs/c8-labs-repo/toolkit-c8-labs-32:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9010
        volumeMounts:
          - name: zeebe-ca-crt
            mountPath: /app/certs
            readOnly: true
        env:
          - name: TASKLIST_API_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: identity-secret-for-components
                key: tasklist-api-secret
          - name: ZEEBE_API_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: identity-secret-for-components
                key: zeebe-api-secret
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9010
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
        - name: zeebe-ca-crt
          secret:
            secretName: "c8-labs-32-zeebe-ca-crt"
---
apiVersion: v1
kind: Service
metadata:
  name: toolkit-service
  namespace: c8-labs-32
spec:
  selector:
    app: toolkit-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9010
