apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-static-web-app
  namespace: ${UNAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-static-web-app
  template:
    metadata:
      labels:
        app: nginx-static-web-app
    spec:
      containers:
      - name: nginx-static-web-app
        image: ${WEBPAGEAPPURL}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-landing-page-service
  namespace: ${UNAMESPACE}
spec:
  selector:
    app: nginx-static-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
