apiVersion: v1
kind: Secret
metadata:
  name: identity-secret-for-components
type: Opaque
data:
  operate-secret: bWFrZWxhYnM=
  tasklist-secret: bWFrZWxhYnM=
  optimize-secret: bWFrZWxhYnM=
  connectors-secret: bWFrZWxhYnM=
  console-secret: bWFrZWxhYnM=
  keycloak-secret: bWFrZWxhYnM=
  zeebe-secret: bWFrZWxhYnM=
  identity-firstuser-password: bWFrZWxhYnM=
  # identityKeycloak.auth.passwordSecretKey
  admin-password: bWFrZWxhYnM=
  password: bWFrZWxhYnM=
  postgres-password: bWFrZWxhYnM=
  # below are keys used by connector for invoking external api
  cep-not-in-use-access-token: bWFrZWxhYnM=
