# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:

extraScrapeConfigs: |
   - job_name: 'zeebe'
     scrape_interval: 15s
     metrics_path: /zeebe/actuator/prometheus
     scheme: https
     tls_config:
       insecure_skip_verify: true
     static_configs:
     - targets:
         - 'c86-mini-x3.makelabs.in'
