# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:

extraScrapeConfigs: |
   - job_name: 'zeebe-gateway'
     scrape_interval: 15s
     metrics_path: /zeebe/actuator/prometheus
     scheme: http
     tls_config:
       insecure_skip_verify: true
     static_configs:
     - targets:
         - 'camunda-zeebe-gateway:9600'
   - job_name: 'zeebe'
     scrape_interval: 15s
     metrics_path: /actuator/prometheus
     scheme: http
     tls_config:
       insecure_skip_verify: true
     static_configs:
     - targets:
         - 'camunda-zeebe-0.camunda-zeebe.c86-mini.svc.cluster.local:9600'
         - 'camunda-zeebe-1.camunda-zeebe.c86-mini.svc.cluster.local:9600'
         - 'camunda-zeebe-2.camunda-zeebe.c86-mini.svc.cluster.local:9600'
