# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ${UNAMESPACE}
  name: team-developer-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete" ]
  # 
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
  # 
- apiGroups: ["storage.k8s.io"] # The storage API group for StorageClasses
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch","create"]
  #
---
# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-developer-rb-${UNAME}
  namespace: ${UNAMESPACE}
subjects:
- kind: User
  name: "${UNAME}"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: team-developer-role
  apiGroup: rbac.authorization.k8s.io
