connectors:
  env:
     - name: CAMUNDA_CONNECTOR_SECRETPROVIDER_ENVIRONMENT_PREFIX
       value: CEP_SECRETS_
     - name: CEP_SECRETS_CUSTOMER_APP_SECRET
       value: do-not-use-this-app-secret-use-below-token-instead
     - name: CEP_SECRETS_EMAIL_APP_ACCESS_TOKEN
       valueFrom:
         secretKeyRef:
           name: identity-secret-for-components
           key: cep-email-access-token

  image:
    pullSecrets:
      - name: registry-docker-hub
