connectors:
  extraVolumeMounts:
    - name: ${UNAMESPACE}-zeebe-ca-crt
      mountPath: /config/certs
      readOnly: true
    - name: zeebe-toolkit-crt
      mountPath: /config/jks
      readOnly: true      
  extraVolumes:
    - name: ${UNAMESPACE}-zeebe-ca-crt
      secret:
        secretName: ${UNAMESPACE}-zeebe-ca-crt
    - name: zeebe-toolkit-crt
      secret:
        secretName: ${UNAMESPACE}-zeebe-toolkit-jks

  env:
  # see https://docs.camunda.io/docs/self-managed/connectors-deployment/connectors-configuration/?configuration=sm
    - name: JAVA_TOOL_OPTIONS
      value: >
        -Djavax.net.ssl.trustStore=/config/jks/${UNAMESPACE}-zeebe-toolkit.jks
        -Djavax.net.ssl.trustStorePassword=changeit
        -Djavax.net.ssl.trustStoreType=JKS  
    - name: CAMUNDA_CONNECTOR_SECRETPROVIDER_ENVIRONMENT_PREFIX
      value: CEP_SECRETS_
    - name: CEP_SECRETS_CUSTOMER_APP_SECRET
      value: do-not-use-this-app-secret-use-below-token-instead
    - name: CEP_SECRETS_EMAIL_APP_ACCESS_TOKEN
      valueFrom:
        secretKeyRef:
          name: identity-secret-for-components
          key: cep-email-access-token

  image:
    pullSecrets:
      - name: registry-docker-hub
  
  configuration: |
    server:
      port: 8080
      servlet:
        context-path: "/connectors"

    management:
      context-path: /actuator
      endpoints:
        web:
          exposure:
            include: metrics,health,prometheus
      endpoint:
        health:
          show-details: always
          show-components: always
          group:
            readiness:
              include:
              - processDefinitionImport
              - zeebeClient

    camunda:
      client:
        rest-address: http://c8-labs-hampi-zeebe-gateway:8080/
        grpc-address: http://c8-labs-hampi-zeebe-gateway:26500
        worker:
          defaults:
            max-jobs-active: 32
            stream-enabled: true
        mode: selfManaged
        auth:
          token-url: https://c8-labs-hampi.makelabs.in/auth/realms/camunda-platform/protocol/openid-connect/token
          client-id: "connectors"
          client-secret: ${VALUES_CAMUNDA_IDENTITY_CLIENT_SECRET}
          audience: "orchestration-api"
      connector:
        headless:
          service-url: "c8-labs-hampi-connectors-headless"
        webhook:
          enabled: true
        polling:
          enabled: true
        agenticai:
          enabled: true

    logging:
      level:
        io.camunda.connector: INFO
