controller:
  extraVolumes:
    - name: custom-ca
      secret:
        secretName: custom-ca
  extraVolumeMounts:
    - name: custom-ca
      mountPath: /etc/nginx/custom-ca
      readOnly: true
  extraArgs: {}
    # Path to the CA certs
    # Below arg is not supported in version 1.31.1 onwards
    #tls-backend-ca-cert: /etc/nginx/custom-ca/ca.crt
