spring:
  application:
    name: tasklist-toolkit

server:
  port: 9010

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# Below is insecure config that works
zeebe:
  client:
    broker:
      gateway-address: c8-labs-32-zeebe-gateway.c8-labs-32.svc.cluster.local:26500
    security:
      plaintext: true
