spring:
  application:
    name: tasklist-toolkit

server:
  port: 9010

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# Below is oauth config for self managed
camunda:
  client:
    mode: self-managed
    auth:
      client-id: zeebe-api
      client-secret: ${ZEEBE_API_TOKEN_SECRET}
      token-url: https://c8-labs-32.makelabs.in/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://c8-labs-32-zeebe-gateway.c8-labs-32.svc.cluster.local:26500
      prefer-rest-over-grpc: false
      audience: zeebe-api

logging:
  level:
    root: INFO
    io.camunda: INFO
    io.grpc: INFO
