spring:
  application:
    name: tasklist-toolkit
  main:
    allow-bean-definition-overriding: true

server:
  port: 9010

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# Below is oauth config for self managed
camunda:
  client:
    mode: self-managed
    auth:
      method: oidc
      client-id: orchestration
      client-secret: ${ZEEBE_TOKEN_SECRET}
      issuer-url: https://${UNAMESPACE}.makelabs.in/auth/realms/camunda-platform
      token-url:  https://${UNAMESPACE}.makelabs.in/auth/realms/camunda-platform/protocol/openid-connect/token
      audience: zeebe-api
    # Absolute path to your server's CA or public certificate - in pem format
    # ca-certificate-path:: ${CA_CERT_PATH}
    grpc-address: grpc://${UNAMESPACE}-zeebe-gateway:26500
    rest-address: http://${UNAMESPACE}-zeebe-gateway:8080
    prefer-rest-over-grpc: false

logging:
  level:
    root: INFO
    io.camunda: INFO
    io.grpc: INFO
